# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='date',
            new_name='appoint_date',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='time',
            new_name='appoint_time',
        ),
    ]
