# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-08 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_auto_20170508_0352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appoint_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appoint_time',
            field=models.TimeField(),
        ),
    ]
